name: CI Feature to Develop

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m unittest discover -s src/tests
          
      - name: Merge to develop
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            const github = require('@actions/github');
            const context = github.context;
            const { owner, repo } = context.repo;
            const pullRequestNumber = context.payload.pull_request.number;

            await github.rest.pulls.merge({
              owner,
              repo,
              pull_number: pullRequestNumber
            });